export const professions = [
    "Administrador",
    "Advogado",
    "Agente de viagens",
    "Agrônomo",
    "Almoxarife",
    "Analista de mercado",
    "Analista de sistemas",
    "Arquiteto",
    "Assistente administrativo",
    "Assistente de marketing",
    "Atendente",
    "Auditor",
    "Biomédico",
    "Biólogo",
    "Cabelereiro",
    "Caixa",
    "Contador",
    "Coordenador de projetos",
    "Designer gráfico",
    "Designer de interiores",
    "Editor de vídeo",
    "Educador físico",
    "Enfermeiro",
    "Engenheiro civil",
    "Engenheiro de segurança do trabalho",
    "Engenheiro eletrônico",
    "Engenheiro de software",
    "Escritor",
    "Estatístico",
    "Estudante",
    "Farmacêutico",
    "Fisioterapeuta",
    "Fotógrafo",
    "Geógrafo",
    "Geólogo",
    "Gestor de tráfego",
    "Guarda municipal",
    "Infografista",
    "Informático",
    "Jardineiro",
    "Jornalista",
    "Médico",
    "Nutricionista",
    "Professor",
    "Psicólogo",
    "Publicitário",
    "Químico",
    "Recepcionista",
    "Redator",
    "Relacionamento com o cliente",
    "Servente",
    "Técnico em enfermagem",
    "Técnico em informática",
    "Veterinário",
    "Web designer",
    "Acadêmico",
    "Acompanhante terapêutico",
    "Agente comunitário",
    "Analista de qualidade",
    "Antropólogo",
    "Arqueólogo",
    "Assistente social",
    "Auditor fiscal",
    "Bancário",
    "Cartógrafo",
    "Chef de cozinha",
    "Cinematógrafo",
    "Cipriano",
    "Climatologista",
    "Coordenador pedagógico",
    "Criador de conteúdo",
    "Cristaloterapeuta",
    "Curador",
    "Dançarino",
    "Diarista",
    "Dietista",
    "Economista",
    "Educador popular",
    "Eletricista",
    "Emergencista",
    "Engenheiro ambiental",
    "Engenheiro de produção",
    "Engenheiro florestal",
    "Estagiário",
    "Facilitador",
    "Físico",
    "Florista",
    "Freelancer",
    "Gerente de vendas",
    "Guia de turismo",
    "Historiador",
    "Ilustrador",
    "Impressor",
    "Infante",
    "Instrutor de pilotagem",
    "Inspetor",
    "Interface Designer",
    "Intérprete",
    "Intuitivo",
    "Jardineiro paisagista",
    "Jogador de futebol",
    "Juiz",
    "Lavrador",
    "Líder de equipe",
    "Mestre de obras",
    "Motoqueiro",
    "Movimentador de estoques",
    "Multimídia",
    "Musicoterapeuta",
    "Narrador",
    "Neuropsicólogo",
    "Olheiro",
    "Organizador de eventos",
    "Paquistanês",
    "Personal trainer",
    "Piloto",
    "Planejador financeiro",
    "Policial",
    "Programador",
    "Promotor de vendas",
    "Proprietário de empresa",
    "Psicopedagogo",
    "Publicitário digital",
    "Químico industrial",
    "Radialista",
    "Relações públicas",
    "Representante comercial",
    "Revendedor",
    "Segments",
    "Segurança do trabalho",
    "Secretário",
    "Sorveteiro",
    "Sustentador",
    "Taxista",
    "Terapeuta",
    "Técnico agrícola",
    "Técnico de manutenção",
    "Técnico em telecomunicações",
    "Vendedores",
    "Vigilante",
    "Zootecnista",
    "Atuário",
    "Cientista de dados",
    "Confeiteiro",
    "Desenvolvedor de software",
    "Motivador",
    "Oficial de justiça",
    "Operador de caixa",
    "Pedagogo",
    "Promotor de justiça",
    "Revisão de texto",
    "Roteirista",
    "Salva-vidas",
    "Serviços gerais",
    "Sondador",
    "Técnico em biomedicina",
    "Técnico em segurança eletrônica",
    "Técnico mecânico",
    "Técnico químico",
    "Teólogo",
    "Torneiro mecânico",
    "Treinador",
    "Vigilante sanitário",
    "Assistente de recursos humanos",
    "Coordenador de comunicação",
    "Analista de dados",
    "Consultor financeiro",
    "Desenhista industrial",
    "Maquinista",
    "Produção cultural",
    "Psicopedagogo clínico",
    "Consultor de marketing",
    "Diretor de arte",
    "Gerente deRH",
    "Palestrante",
    "Product owner",
    "Redator publicitário",
    "Responsável técnico",
    "Arquivista",
    "Cervejeiro",
    "Controlador de tráfego",
    "Economista de recursos naturais",
    "Engenheiro de segurança",
    "Gerente de TI",
    "Intercambista",
    "Pesquisador",
    "Técnico em cardíaca",
    "Auditor de sistemas",
    "Especialista em cadastros",
    "Engenheiro agrônomo",
    "Gestor de operações",
    "Mediador de conflitos",
    "Pesquisador de mercado",
    "Psicólogo organizacional",
    "Tecnólogo em marketing",
    "Transcritor",
    "Webmaster",
    "Analista de suporte técnico",
    "Gerente de projeto",
    "Pilotagem de drones",
    "Mecânico",
    "Negoceador",
    "Técnico em geologia"
];


export const salarium = [
    "Selecione",
    "Entre R$1.300,00 até R$2.500,00",
    "Entre R$2.500,00 até R$5.000,00",
    "Entre R$5.000,00 até R$10.000,00",
    "Entre R$10.000,00 até R$25.000,00",
    "Mais de R$25.000,00"
]